version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/guestbook
permissions:
   - object: /var/www/guestbook
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - file
